
<h1 style="text-align: center; color: purple;" markdown="1">Econ 320 Python Lab. A First Look at the Woodridge Data </h1>
<h2 style="text-align: center; color: purple;" markdown="1">Handout 1 </h2>

# The package set up 
Most of the packages that you have used so far are installed in the Anaconda or VSCode but many other useful packages need to be installed. 
Here is how you do it. 

In the terminal or command window install the package wooldrigde by using the line of code below

`pip install wooldridge`
<br>
or 
<br>
`conda install wooldridge`

**or even easier use the ! sing in a jupyter notebook cell, this opens a bash window in the back for you and installs the packages that are not preinstalled in Anaconda.**

`!pip install wooldridge` 

<br>

> If you are working with cloud computing pacakges need to be install in every session. (Google colab, DataCamp workspace AWS etc)

> If working with traditional computing (your computer) if a package is already installed you will get a message you don't need to install it again. 

> **Recommended:** Hide the output of the installation using 
`%%capture`  this will hide the output.

In [8]:
%%capture  
!pip install wooldridge
!pip install termcolor

#### Import the necessary packages into your notebook

The wooldridge package contains all the datasets from your textbook. It saves you time because now you don't have to look for these online and import them. They come with the package. 
However there is also possible to access the datasets by importing those directly from the website

In [9]:
# After having installed the package you need to import the package into your 
# notebook to access the datasets. 
# import the other neccesary packages here
import wooldridge as woo
import numpy as np 
import pandas as pd

# import packages for graphs
import matplotlib.pyplot as plt
import seaborn as sns

affairs = woo.dataWoo("affairs")

#describe the data with only 3 decimal places
pd.options.display.float_format = "{:.3f}".format

# Inspect your data to support your hypothesis. 

We are going to be working with the `affairs` data from Wooldridge, this datasets contains variables related to the characteristics of marriages and whether or not there have been affairs in these marriages. We will inspect the data and explore the relationship between marriange happiness and having kids by looking at some crosstabulation of variables.

In [10]:
# load data named <dataset> and save it in an object with the same name
# if you are using the package wooldridge you can use the following code


# If not using the package wooldridge or this is not working 
# You can download your dataset using the options below 
# Downloading and reading the data (Stata format)
affairs1 = pd.read_stata('http://fmwww.bc.edu/ec-p/data/wooldridge/affairs.dta')

# Use info.() to inspect your data set, the variables but also the types. But do not forgte to look at the codebook. 
affairs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 601 entries, 0 to 600
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        601 non-null    int64
 1   male      601 non-null    int64
 2   age       601 non-null    float64
 3   yrsmarr   601 non-null    float64
 4   kids      601 non-null    int64
 5   relig     601 non-null    int64
 6   educ      601 non-null    int64
 7   occup     601 non-null    int64
 8   ratemarr  601 non-null    int64
 9   naffairs  601 non-null    int64
 10  affair    601 non-null    int64
 11  vryhap    601 non-null    int64
 12  hapavg    601 non-null    int64
 13  avgmarr   601 non-null    int64
 14  unhap     601 non-null    int64
 15  vryrel    601 non-null    int64
 16  smerel    601 non-null    int64
 17  slghtrel  601 non-null    int64
 18  notrel    601 non-null    int64
dtypes: float64(2), int64(17)
memory usage: 89.3 KB

In [11]:
# Use method describe() to look at describe statistics of your data.
affairs.describe()
# Easier than this is to change the display options in the package set up cell above.

,id,male,age,yrsmarr,kids,relig,educ,occup,ratemarr,naffairs,affair,vryhap,hapavg,avgmarr,unhap,vryrel,smerel,slghtrel,notrel
count,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000,601.000
mean,1059.722,0.476,32.488,8.178,0.715,3.116,16.166,4.195,3.932,1.456,0.250,0.386,0.323,0.155,0.110,0.116,0.316,0.215,0.273
std,914.905,0.500,9.289,5.571,0.452,1.168,2.403,1.819,1.103,3.299,0.433,0.487,0.468,0.362,0.313,0.321,0.465,0.411,0.446
min,4.000,0.000,17.500,0.125,0.000,1.000,9.000,1.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,528.000,0.000,27.000,4.000,0.000,2.000,14.000,3.000,3.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
50%,1009.000,0.000,32.000,7.000,1.000,3.000,16.000,5.000,4.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
75%,1453.000,1.000,37.000,15.000,1.000,4.000,18.000,6.000,5.000,0.000,0.000,1.000,1.000,0.000,0.000,0.000,1.000,0.000,1.000
max,9029.000,1.000,57.000,15.000,1.000,5.000,20.000,7.000,5.000,12.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000

**Notice** the descriptive stats for some of the variables do not make sense.   
**For example:** What does a mean of 3.16 mean for the religion variable. 

When we analyse data we need to **read** what we present, a code that runs does not guarantee meanignfull data analysis.

In [12]:

#average number of affairs for kids =0

In [13]:
#pivot table of average number of affairs for each category of kids

### Practice inspecting datasets

Taken from Wooldridge computer exercise 2 chapter 1. 

Use the data in BWGHT to answer this question. 
the description of this dataset is here 

http://fmwww.bc.edu/ec-p/data/wooldridge/bwght.des

* (i)	How many women are in the sample, and how many report smoking during pregnancy?
* (ii)	What is the average number of cigarettes smoked per day? 
* (iii)	Among women who smoked during pregnancy, what is the average number of cigarettes smoked per day? 
* (iv)	Find the average of fatheduc in the sample. Why are only 1,192 observations used to compute this average?
* (v)	Report the average family income and its standard deviation in dollars.

In [14]:
#Load data 
bwght = woo.dataWoo('bwght')

# Translate the following into Python using Pandas 
# shape method provides a vector with the dimensions of an array in python,
# the element in the first  position, 0, represents rows, shape[0]
# the element in the second  position, 1, represents rows, shape[1]
women = 
smokepreg=
avgcig= 
smoke_avgcig=
fatheducobs= 
avgfathereduc = 
faminct = 

print(f'Number of women: {women}')
print(f'Number of women that smoke during pregnancy: {smokepreg}')
print(f'Average number of cigarettes smoked per day: {round(avgcig, 3)}')
print(f'Average number of cigarettes smoked per day, among smokers: {round(smoke_avgcig,3)}')
print(f'Average of fatheduc in the sample: {round(avgfathereduc, 3)}')
print(f'Number of observations that have fathers education: {fatheducobs}')
print(f'Average family income: {round(faminct, 2)}')
#family income standard deviation
print(f'Family income std: {round(faminct.std(), 2)}')

SyntaxError: invalid syntax (63682652.py, line 8)


## Correlations

Let's look back at our CEO salary data ceosal1

* extract the variables roe, salary and sales and calculate the correlations among those, name the object cormat and use parenthesis to print the object.

In [ ]:
# read data from Wooldridge's package
ceosal1 = woo.dataWoo('ceosal1')

Let's look at the correlation plots (More on this next class)

In [ ]:
ceosal1.corr()

### What is seaborn?
Seaborn is a library for making statistical graphics in Python. It builds on top of matplotlib and integrates closely with pandas data structures. Seaborn helps you explore and understand your data.

In [ ]:
# Set theme and style
#sns.set_style('white')
#sns.set_context('paper')
#sns.set_style('ticks')
# Basic correlogram
#sns.pairplot(ceosal1)
plt.matshow(ceosal1.corr())
plt.show()

In [ ]:
# Use this line of code to print this handout into html 
!jupyter nbconvert --to html H1_320Lab__Wooldridgedata.ipynb


<style>
div.gray { background-color:#dbdbdb; border-radius: 5px; padding: 20px;}
</style>
<div class = "gray">

**Packages used in this document**

`wooldridge`
`matplot.lib`
`pandas`
`numpy` 
`seaborn`
    

</div>

</div>

<br>

&nbsp;

<hr />

<p style="text-align: center;">ECON320 Python Programming Laboratory</a></p>
<p style="text-align: center;">Professor <em> Paloma Lopez de mesa Moyano</em></a></p>
<p style="text-align: center;"><span style="color: #6666FF;"><em>paloma.moyano@emory.edu</em></span></p>

<p style="text-align: center;">Department of Economics</a></p>
<p style="text-align: center;">Emory University</a></p>

&nbsp;